### PR TITLE
added amuse option for horizontal grid

### PR DESCRIPTION
**Pull request by mchertova**
do not merge yet

### CODE REVIEW

**Comment by ipelupessy** [comment]
@benvanwerkhoven @mchertova currently the PR has a hard coded lat and lon range in horiz_grid_amuse. It is possible to change it so that it takes the ULON_G and ULAN_G as input (ie assuming its get set beforehand) then it could:
  - assume the input to conform to a cartesian grid with eg ```dlon=ULON_G(2,1)-ULON_G(1,1)``` and calculate the remaining quantities HTN, HTE etc with more or less the same formula
or
  - not make this assumption, and allow for general curvilinear orthogonal grid

In the former case it makes sense to add parameters for the south-west and north-east corner coordinates or something and fill ULON_G and ULAT_G in the interface, while in the latter case ULON_G and ULAT_G could be exposed directly (to be set in the python layer)

what do you think?

**Comment by mchertova** [comment]
If we are talking only about changes of grid definition for the amuse case (which is currently used for benchmark) I would go for the first option. In the paper with the description of the benchmark they use simple cartesian grid as well.

**Comment by ipelupessy** [comment]
yea, I am also gravitating towards that..also because that is easiest to use (otherwise you depend on the user setting correct (non-trivial) ULON_G and ULAT_G grids)

**Comment by benvanwerkhoven** [comment]
It depends on what you want to do. I think the latter is more generic, and leaves room to do more in the Python interface and less inside the Fortran code. The interface could then generate the global latlons for the U grid based on some description by the user. On the other hand, if you don't need all of that right now, I think the first option is fine.

**Comment by ipelupessy** [comment]
this is superseded by PR #4 ?

**Comment by ipelupessy** [comment]
close because of #4

**Pull request closed without merging**
